# Generated by Django 3.2.23 on 2024-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdataset',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='mnt/c/CS_480_Stuff/bus-labeling/src/media/datasets/', verbose_name='Dataset Path'),
        ),
    ]
