# Generated by Django 3.2.23 on 2024-03-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_alter_busdataset_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdataset',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/mnt/c/CS_480_Stuff/bus-labeling/src/media/datasets/', verbose_name='Dataset Path'),
        ),
        migrations.CreateModel(
            name='SplitDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('percentage', models.IntegerField()),
                ('data', models.TextField()),
                ('original_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_datasets', to='labeling.busdataset')),
            ],
        ),
    ]
