# Generated by Django 3.2.23 on 2024-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_auto_20240314_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='birads',
            name='diagnosis',
            field=models.BooleanField(default=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='busdataset',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/mnt/c/BryanTestCase/bus-labeling-copy/bus-labeling-copy/src/media/datasets/', verbose_name='Dataset Path'),
        ),
    ]
