# Generated by Django 3.2.23 on 2024-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0004_auto_20240321_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCheckpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(choices=[('SAM', 'SAM'), ('MAE', 'MAE')], max_length=3)),
                ('checkpoint_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='busdataset',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/mnt/c/BryanTestCase/bus-labeling-copy/media/datasets/', verbose_name='Dataset Path'),
        ),
    ]
