# Generated by Django 3.2.23 on 2024-04-03 00:19

from django.db import migrations


def create_initial_checkpoint(apps, schema_editor):
    ModelCheckpoint = apps.get_model('labeling', 'ModelCheckpoint')
    ModelCheckpoint.objects.create(
        model_name='Official',
        model_type='MAE',
        checkpoint_path='/src/MedAI/checkpoint.pth/'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_auto_20240402_1537'),
    ]

    operations = [
        migrations.RunPython(create_initial_checkpoint),
    ]
