# Generated by Django 3.2 on 2024-04-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_auto_20240402_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcheckpoint',
            old_name='checkpoint_path',
            new_name='checkpoint_name',
        ),
    ]
